name: Deploying Azure Webapp

env:
  OUTPUT_PATH: ${{ github.workspace }}
  RESOURCE_GROUP_REGION: eastus
  SERVER_NAME: gihtubactions

on:
  workflow_dispatch:

jobs:
      
  # Deploying Azure Webapp
  DeployVM:
    runs-on: windows-latest

    steps:
    # Deploying Azure Webapp
    - name: checkout repo
      uses: actions/checkout@v1

    - name: look for ps1 file
      run: |
        ls '${{ env.OUTPUT_PATH }}'
    - name: Deploying Azure Webapp
      run: >
          powershell -command "& '${{ env.OUTPUT_PATH }}/deploy-webapp.ps1'"  
          -azureSubscriptionName ${{ secret.AZURE_SUBSCRIPTION_ID }}
          -resourceGroupNameRegion ${{ env.RESOURCE_GROUP_REGION }}
          -serverName ${{ env.SERVER_NAME }} 
          -adminLogin ${{ secret.ADMIN_LOGIN }}
          -deploymentid ${{ secret.DeploymentID }}
          -DOCKERHUB_PASSWORD ${{ secret.DOCKERHUB_PASSWORD }}
          -DOCKERHUB_USERNAME ${{ secret.DOCKERHUB_USERNAME }}
          -Username ${{ secret.Username }}
          -Password ${{ secret.Password }}
