name: deploy an sample web application

on:
  push:
    branches:
    - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
        - name: Checkingout code
          uses: action/checkout@v4

        - name: Install ngnix on ec2
          uses: appleboy/ssh-action@v1
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.username }}
            password: ${{ secrets.key_path }}
            port: ${{ secrets.PORT }}
            script: |
                whoami
                

    
    
