name: deploy an sample web application

'on':
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkingout code
        uses: actions/checkout@v4

      - name: ssh into server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            sudo apt update
            sudo apt install -y python3
            sudo apt install -y docker.io
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo gpasswd -a $USER docker
            exit 0
      
      - name: Build Docker image
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            mkdir -p docker
            cd docker
            git clone https://github.com/msshashank1997/TravelMemory.git

            cd TravelMemory
            git pull
            sudo chmod 777 -R checkcommit.py
            pip install -r requirements.txt

            # replace the PAT with ${{ secrets.PAT }} in checkcommit.py file
            sed -i 's|PAT = ".*"|PAT = "${{ secrets.PAT }}"|' checkcommit.py

            python3 checkcommit.py
            if [ $? -ne 0 ]; then
              echo "No new commits found. Exiting..."
              exit 0
            else
              echo "New commits found. Proceeding with deployment..."
              # Build the Docker image
              cd backend
              # Create .env file with MongoDB connection info
              sed -i 's|MONGO_URI=".*"|MONGO_URI="${{ secrets.MONGO_URI }}"|' .env
              
              # Check if any container is using port 3001 and remove it
              CONTAINER_ID=$(docker ps -q --filter publish=3001)
              if [ ! -z "$CONTAINER_ID" ]; then
                echo "Found container using port 3001, removing it..."
                docker stop $CONTAINER_ID
                docker rm $CONTAINER_ID
                docker build -t travelmemory-backend .
                docker run -d -p 3001:3001 --name travelmemory-backend travelmemory-backend
                # Check if the container started successfully
                if [ $? -eq 0 ]; then
                  echo "Container started successfully."
                else
                  echo "Failed to start the container."
                  exit 1
                fi
              else
                # No container found, just build and run
                docker build -t travelmemory-backend .
                docker run -d -p 3001:3001 --name travelmemory-backend travelmemory-backend
                if [ $? -eq 0 ]; then
                  echo "Container started successfully."
                else
                  echo "Failed to start the container."
                  exit 1
                fi
              fi
            fi
